=== xtremebrat/DB/Xquery/review.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="RatingType"> 
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/> 
			<xsd:maxInclusive value="5"/> 
		</xsd:restriction> 
	</xsd:simpleType>
	<xsd:element name="BookReviews">
		<xsd:complexType> 
			<xsd:sequence>
				<xsd:element name="Review" maxOccurs="unbounded"> 
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Review_ID" type="xsd:string" minOccurs="1" maxOccurs="1"/>
							<xsd:element name="Book_Title" type="xsd:string" minOccurs="1" maxOccurs="1"/> 
							<xsd:element name="Rating" type="RatingType" minOccurs="1" maxOccurs="1"/> 
							<xsd:element name="Reviewer" type="xsd:string" minOccurs="1" maxOccurs="1"/>
							<xsd:element name="Review_Description" type="xsd:string" minOccurs="0" maxOccurs="1"/> 
							<xsd:element name="Review_Date" type="xsd:date" minOccurs="1" maxOccurs="1"/> 
						</xsd:sequence> 
					</xsd:complexType>
				</xsd:element> 
			</xsd:sequence>
		</xsd:complexType> 
	</xsd:element>
</xsd:schema>

=== xtremebrat/DB/Xquery/review.xml
<?xml version="1.0"?>
<BookReviews xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="review.xsd">
	<Review>
		<Review_ID>201</Review_ID>
		<Book_Title>All the President's Men</Book_Title>
		<Rating>3</Rating>
		<Reviewer>Hilde Bygdevoll</Reviewer>
		<Review_Description>An important book in contemporary American history</Review_Description>
		<Review_Date>1995-10-25</Review_Date>
	</Review>
	<Review>
		<Review_ID>202</Review_ID>
		<Book_Title>Life After Life</Book_Title>
		<Rating>4</Rating>
		<Reviewer>Jason A. Miller</Reviewer>
		<Review_Description>Good Read
</Review_Description>
		<Review_Date>2014-04-04</Review_Date>
	</Review>
	<Review>
		<Review_ID>203</Review_ID>
		<Book_Title>Allegiant</Book_Title>
		<Rating>5</Rating>
		<Reviewer>MomoMonique</Reviewer>
		<Review_Description>Good Read
</Review_Description>
		<Review_Date>2013-10-22</Review_Date>
	</Review>
	<Review>
		<Review_ID>204</Review_ID>
		<Book_Title>A Game of Thrones</Book_Title>
		<Rating>1</Rating>
		<Reviewer>MISTER SJEM</Reviewer>
		<Review_Description>Well plotted and paced; excellent, fresh fantasy tale
</Review_Description>
		<Review_Date>2014-01-01</Review_Date>
	</Review>
	<Review>
		<Review_ID>205</Review_ID>
		<Book_Title>Still Life with Bread Crumbs</Book_Title>
		<Rating>2</Rating>
		<Reviewer>Dan Rather</Reviewer>
		<Review_Description>Really, Bread crumbs?</Review_Description>
		<Review_Date>2014-02-18</Review_Date>
	</Review>
	<Review>
		<Review_ID>206</Review_ID>
		<Book_Title>A Song of Ice and Fire</Book_Title>
		<Rating>1</Rating>
		<Reviewer>Hilde Bygdevoll</Reviewer>
		<Review_Description>Not of my interest</Review_Description>
		<Review_Date>2014-01-16</Review_Date>
	</Review>
	<Review>
		<Review_ID>207</Review_ID>
		<Book_Title>Alex Cross, Run</Book_Title>
		<Rating>3</Rating>
		<Reviewer>Jason A. Miller</Reviewer>
		<Review_Description>Average</Review_Description>
		<Review_Date>2013-07-04</Review_Date>
	</Review>
	<Review>
		<Review_ID>208</Review_ID>
		<Book_Title>All the President's Men</Book_Title>
		<Rating>3</Rating>
		<Reviewer>Brian D. Rubendall</Reviewer>
		<Review_Description>Maybe the single greatest reporting effort of all time</Review_Description>
		<Review_Date>2014-12-12</Review_Date>
	</Review>
	<Review>
		<Review_ID>209</Review_ID>
		<Book_Title>Allegiant</Book_Title>
		<Rating>3</Rating>
		<Reviewer>Penny</Reviewer>
		<Review_Description>This ending was not that ending</Review_Description>
		<Review_Date>2013-11-16</Review_Date>
	</Review>
	<Review>
		<Review_ID>210</Review_ID>
		<Book_Title>Still Life with Bread Crumbs</Book_Title>
		<Rating>4</Rating>
		<Reviewer>Brian D. Rubendall</Reviewer>
		<Review_Description>Good work</Review_Description>
		<Review_Date>2014-01-29</Review_Date>
	</Review>
	<Review>
		<Review_ID>211</Review_ID>
		<Book_Title>A Heartbreaking Work of Staggering Genius</Book_Title>
		<Rating>4</Rating>
		<Reviewer>MomoMonique</Reviewer>
		<Review_Description></Review_Description>
		<Review_Date>2005-08-08</Review_Date>
	</Review>
	<Review>
		<Review_ID>212</Review_ID>
		<Book_Title>A Game of Thrones</Book_Title>
		<Rating>4</Rating>
		<Reviewer>Jason A. Miller</Reviewer>
		<Review_Description>Real fun</Review_Description>
		<Review_Date>2014-01-15</Review_Date>
	</Review>
	<Review>
		<Review_ID>213</Review_ID>
		<Book_Title>Life After Life</Book_Title>
		<Rating>3</Rating>
		<Reviewer>Penny</Reviewer>
		<Review_Description>well written</Review_Description>
		<Review_Date>2014-04-05</Review_Date>
	</Review>
	<Review>
		<Review_ID>214</Review_ID>
		<Book_Title>Allegiant</Book_Title>
		<Rating>5</Rating>
		<Reviewer>Dan Rather</Reviewer>
		<Review_Description>Teen's read</Review_Description>
		<Review_Date>2014-01-10</Review_Date>
	</Review>
	<Review>
		<Review_ID>215</Review_ID>
		<Book_Title>Alex Cross, Run</Book_Title>
		<Rating>3</Rating>
		<Reviewer>Penny</Reviewer>
		<Review_Description>Read it if you like it</Review_Description>
		<Review_Date>2013-08-25</Review_Date>
	</Review>
	<Review>
		<Review_ID>216</Review_ID>
		<Book_Title>Still Life with Bread Crumbs</Book_Title>
		<Rating>2</Rating>
		<Reviewer>Penny</Reviewer>
		<Review_Description>Not so interesting</Review_Description>
		<Review_Date>2014-01-30</Review_Date>
	</Review>
	<Review>
		<Review_ID>217</Review_ID>
		<Book_Title>All the President's Men</Book_Title>
		<Rating>5</Rating>
		<Reviewer>Dan Rather</Reviewer>
		<Review_Description>An Authentic thriller</Review_Description>
		<Review_Date>2014-05-12</Review_Date>
	</Review>
	<Review>
		<Review_ID>218</Review_ID>
		<Book_Title>A Song of Ice and Fire</Book_Title>
		<Rating>4</Rating>
		<Reviewer>MISTER SJEM</Reviewer>
		<Review_Description></Review_Description>
		<Review_Date>2014-02-02</Review_Date>
	</Review>
	<Review>
		<Review_ID>219</Review_ID>
		<Book_Title>Still Life with Bread Crumbs</Book_Title>
		<Rating>2</Rating>
		<Reviewer>MISTER SJEM</Reviewer>
		<Review_Description>Not appealing</Review_Description>
		<Review_Date>2014-02-19</Review_Date>
	</Review>
	<Review>
		<Review_ID>220</Review_ID>
		<Book_Title>A Game of Thrones</Book_Title>
		<Rating>5</Rating>
		<Reviewer>Dan Rather</Reviewer>
		<Review_Description>Excellent</Review_Description>
		<Review_Date>2014-01-14</Review_Date>
	</Review>
</BookReviews>
